version: '3'

services:
    mysql-db:
        restart: always
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
            #- ./init.sql:/docker-entrypoint-initdb.d/setup.sql
        networks:
            - backend-network
        environment: 
            MYSQL_ROOT_PASSWORD: frogger
            MYSQL_DATABASE: frogger_db
        command: --init-file /data/application/init.sql
volumes:
    db-data:
      driver: local
  
networks:
    backend-network:
      driver: bridge